(() => {
  const sleep = ms => new Promise(res => setTimeout(res, ms));

  async function waitForContent() {
    let $ = jQuery;
    const thisScriptTag = $(document.currentScript);
    const htmlStructure = [...thisScriptTag.parents()];
    const mainParent = htmlStructure[1];
    let content;
    while (true) {
      content = $(mainParent).find('.module_content');
      if (content.html()) { break; }
      await sleep(20);
    }
    return content;
  }

  async function start() {
    const content = await waitForContent();
    content.append('<p>This is some extra content generated by JavaScript.</p>');
  }

  start();
})();
